[package]
name = "ccdl-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "CLI for ccdl"

[lints]
workspace = true

[[bin]]
name = "ccdl"
path = "src/main.rs"

[features]
default = ["table"]
table = ["ccdl/table"]

[dependencies]
ccdl = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
